Simplified a few functions, add new features: backupallpkg, recompilepkg, recompileallpkg, autorecompilepkg, autorecompileallpkg

diff --git a/libepkg b/libepkg
--- a/libepkg
+++ b/libepkg
@@ -62,6 +62,54 @@ checkargentoverlay () {
 	fi
 }
 
+checkmakeconf () {
+	# function checking the existence and validity of make.conf
+	# in accordance wih gentoo and argentws-build standard
+
+        if [ -e "/etc/portage/make.conf" ] ; then
+                . /etc/portage/make.conf
+        else
+                eerror "The file does not match the pattern of environment script"
+                echo "Please consider using avasile to change to one of the modes"
+                echo "avasile --help"
+        fi
+}
+
+checkportdir () {
+	# function to check the existence of portage and argent/portage.git independent dirs:
+	# distfiles and packages
+
+
+	# the unconventional way here: we import /etc/portage/make.conf into current local function
+	checkmakeconf
+
+        # check if ${PORTDIR} exists
+
+        if [ ! -d "${PORTDIR}" ] ; then
+                eerror "No such directory: ${PORTDIR}"
+                echo "Consider running: epkg update"
+                exit 1
+        fi
+
+        # check if distfiles exist. Again, we might never know what Gentoo users are up to
+
+        if [ ! -d "${PORTDIR}"/distfiles ] ; then
+                eerror "No such directory: ${PORTDIR}/distfiles"
+                echo "Consider creating the directory with the right ownership:"
+                echo "i.e.: chgrp portage ${PORTDIR}/distfiles"
+                exit 1
+        fi
+
+        # check if ${PORTDIR}/packages exists
+
+        if [ ! -d "${PORTDIR}"/packages ] ; then
+                eerror "No such directory: ${PORTDIR}/packages"
+                echo "Consider creating the directory with the right ownership:"
+                echo "i.e.: chgrp portage ${PORTDIR}/packages"
+                exit 1
+        fi
+}
+
 checksync () {
 	checkportagetree
 	checkargentoverlay
@@ -81,13 +129,8 @@ backuppkg () {
 
         # the unconventional way here: we import /etc/portage/make.conf into current local function
 
-        if [ -e "/etc/portage/make.conf" ] ; then
-                . /etc/portage/make.conf
-	else
-		eerror "The file does not match the pattern of environment script"
-		echo "Please consider using avasile to change to one of the modes"
-		echo "avasile --help"
-	fi
+	checkmakeconf
+
 
 	if [[ "$@" = "" ]] ; then
 		eerror "You have not specified any package to backup"
@@ -112,6 +155,32 @@ backuppkg () {
 		exit 1
 	fi
 
+	# regenerating environment here is a must!
+	env-update && source /etc/profile
+}
+
+backupallpkg () {
+	# function to *backup all packages in the system* for future use
+
+
+	# the unconventional way here: we import /etc/portage/make.conf into current local function
+	checkportdir
+
+	eerror "Warning: If you backup everything, make sure you keep the packages safe :)"
+	eerror "We cannot take responsibility of safe-guarding the newly backup-ed up system"
+
+        if [[ "$(readlink -f "/etc/portage/make.conf")" = "/opt/argentws-build/conf/intel/portage/make.conf.amd64-usermode" ]] ; then
+                eerror "You are on --usermode, we propose using: avasile --devmode or --srcmode for this"
+                eerror "If you continue, you continue on your own risk!"
+		eerror "Make sure you keep the backup safe!"
+                sleep 3
+                quickpkg --include-config y --include-unmodified-config y $(qlist -IC)
+        else
+                quickpkg --include-config y --include-unmodified-config y $(qlist -IC)
+        fi
+
+	# regenerating environment here is a must!
+	env-update && source /etc/profile
 }
 
 cleanoutdated () {
@@ -119,13 +188,7 @@ cleanoutdated () {
 
 	# the unconventional way here: we import /etc/portage/make.conf into current local function
 
-	if [ -e "/etc/portage/make.conf" ] ; then
-		. /etc/portage/make.conf
-	else
-		eerror "The file does not match the pattern of environment script"
-		echo "Please consider using avasile to change to one of the modes"
-		echo "avasile --help"
-	fi
+	checkmakeconf
 
 	# we have 2 checks here: if usr/portage and usr/portage/packages really exist
 	# we may never know what users do to their portage dirs in Gentoo system 
@@ -152,13 +215,7 @@ cleanoutdated () {
 cleanlocalpkg () {
         # the unconventional way here: we import /etc/portage/make.conf into current local function
 
-        if [ -e "/etc/portage/make.conf" ] ; then
-                . /etc/portage/make.conf
-        else
-                eerror "The file does not match the pattern of environment script"
-                echo "Please consider using avasile to change to one of the modes"
-                echo "avasile --help"
-        fi
+	checkmakeconf
 
         # function to cleanup all local packages in /usr/portage/packages
         # it also includes deletion of /usr/portage/Packages
@@ -216,17 +273,6 @@ recompileallpkg () {
 	fi
 }
 
-autorecompileallpkg () {
-        # function to recompile everything on the system and also saving all the recompiled packages. Usually in /usr/portage/packages
-
-        if [[ "$(readlink -f "/etc/portage/make.conf")" = "/opt/argentws-build/conf/intel/portage/make.conf.amd64-usermode" ]] ; then
-                eerror "You are not allowed to run in --usermode, we propose using: avasile --devmode or --srcmode for this"
-                exit 1
-        else
-                EMERGE_DEFAULT_OPTS="--rebuilt-binaries" emerge -v $(qlist -IC)
-        fi
-}
-
 autorecompilepkg () {
 
         # function to call a recompile of a package and save it to ${PORTDIR}/packages"
@@ -242,45 +288,24 @@ autorecompilepkg () {
 
 }
 
+autorecompileallpkg () {
+        # function to recompile everything on the system and also saving all the recompiled packages. Usually in /usr/portage/packages
+
+        if [[ "$(readlink -f "/etc/portage/make.conf")" = "/opt/argentws-build/conf/intel/portage/make.conf.amd64-usermode" ]] ; then
+                eerror "You are not allowed to run in --usermode, we propose using: avasile --devmode or --srcmode for this"
+                exit 1
+        else
+                EMERGE_DEFAULT_OPTS="--rebuilt-binaries" emerge -v $(qlist -IC)
+        fi
+}
+
 fetchsourcepkg () {
 	# function to download the source of the program for development / patching purposes
 
 
 	# the unconventional way here: we import /etc/portage/make.conf into current local function
 
-	if [ -e "/etc/portage/make.conf" ] ; then
-		. /etc/portage/make.conf
-        else
-		eerror "The file does not match the pattern of environment script"
-		echo "Please consider using avasile to change to one of the modes"
-		echo "avasile --help"
-	fi
-
-        # check if ${PORTDIR} exists
-
-        if [ ! -d "${PORTDIR}" ] ; then
-                eerror "No such directory: ${PORTDIR}"
-                echo "Consider running: epkg update"
-                exit 1
-        fi
-
-	# check if distfiles exist. Again, we might never know what Gentoo users are up to
-
-	if [ ! -d "${PORTDIR}"/distfiles ] ; then
-		eerror "No such directory: ${PORTDIR}/distfiles"
-		echo "Consider creating the directory with the right ownership:"
-		echo "i.e.: chgrp portage ${PORTDIR}/distfiles"
-		exit 1
-	fi
-
-	# check if ${PORTDIR}/packages exists
-
-	if [ ! -d "${PORTDIR}"/packages ] ; then
-		eerror "No such directory: ${PORTDIR}/packages"
-		echo "Consider creating the directory with the right ownership:"
-		echo "i.e.: chgrp portage ${PORTDIR}/packages"
-		exit 1
-	fi
+	checkportdir
 
 	# function to warn the regular user that he's doin something wrong
 	# but still do it anyway.
@@ -289,7 +314,7 @@ fetchsourcepkg () {
 		eerror "You are on --usermode, we propose using: avasile --devmode or --srcmode for this"
 		eerror "If you continue, you continue on your own risk!"
 		sleep 3
-		EMERGE_DEFAULT_OPTS="--rebuilt-binaries" emerge --fetchonly "$@"	
+		EMERGE_DEFAULT_OPTS="--rebuilt-binaries" emerge --fetchonly "$@"
 	else
 		EMERGE_DEFAULT_OPTS="--rebuilt-binaries" emerge --fetchonly "$@"
 	fi
